### ISSUE TITLE
Create a CM Team Wiki

### ISSUE THREAD

**Issue by arronlacey** [alan-turing-institute/open-research-community-management#205]
### Summary Sentence

This issue proposes that we build a CM Team Wiki that is outward facing and shows how we build Communities and work together as a team of Community Managers. We can try to externalize as much of our internal governance and structures to generalize them for adoption in other Community Management Teams.

### What needs to be done?

- [x] Decide on how it will be built i.e. jupyter book, quarto, mkdocs
- [x] Decide what content we would want to put there
- [ ] Decide how we will generalise this into TTW, when this will happen and who will do each part. 

### Who can help?

Anyone from the CM Team

---

### Update after the issue was opened

[Add details]

**Comment by cassgvp** [comment]
I'll build out a rough sketch of where the RCM oboarding materials and associated links could fit into the wiki.

**Comment by arronlacey** [comment]
> I'll build out a rough sketch of where the RCM oboarding materials and associated links could fit into the wiki.

Thanks @cassgvp that would be really helpful!

**Comment by cassgvp** [comment]
I've been working on this across #226, #225, #219 and #218, and we're making good progress with the wiki!

Still to think about how we generalise it to TTW. Maybe an addition to the collaboration chapter?

**Comment by cassgvp** [comment]
Following discussions in RCM team meetings, the wiki has been moved to a jupyter book format. Currently hosted at https://cassgvp.github.io/open-research-community-management/, for review during RCM Team Day May 2024.

**Comment by cassgvp** [comment]
jupyter book wiki has now been launched! Thank you @BrainonSilicon for building me through!! 🚀 💅🏻 

https://alan-turing-institute.github.io/open-research-community-management/
