### ISSUE TITLE
RCM Wiki Workshop

### ISSUE THREAD

**Issue by arronlacey** [alan-turing-institute/open-research-community-management#218]
### Summary Sentence

Hold a 2 hour workshop session on how to build and contribute to the RCM Wiki

### What needs to be done?

- [x] An overview of Quarto
- [x] Local setup
- [x] How to contribute
- [x] First commit

### Who can help?

Anyone with questions about quarto / wikis will help plan content for the workshop

---

### Update after the issue was opened

[Add details]

**Comment by cassgvp** [comment]
This workshop was successfully run :). Many thanks to @arronlacey for delivery and hosting :).

Can we link to the recording of the session, @malvikasharan ?

**Comment by malvikasharan** [comment]
Yes please. Sorry for the late response here.

**Comment by cassgvp** [comment]
[Notes from the session](https://hackmd.io/rJcGlIS5Rc-IhxZXeIqLPg?edit)

[Session recording-ADD-LINK]() - note this is in our google drive for now as my OneDrive isn't happy!
