### ISSUE TITLE
Add onboarding docs to RCM Wiki

### ISSUE THREAD

**Issue by eirini-zormpa** [alan-turing-institute/open-research-community-management#225]
### Summary Sentence

Add onboarding docs to the RCM Wiki (see also #205).

### What needs to be done?

- [ ] finalise content to be included in the onboarding
- [ ] agree on a process to run onboarding
- [ ] include in the RCM wiki

### Who can help?

- @GabinWK and @cassgvp as the most recent members to have been onboarded
- @malvikasharan 

---

**Comment by malvikasharan** [comment]
Thanks for this issue @eirini-zormpa - can I please ask to also update this issue to match what you all decide to include in the induction: https://github.com/alan-turing-institute/open-research-community-management/blob/main/.github/ISSUE_TEMPLATE/NEW_MEMBERS.md?

**Comment by cassgvp** [comment]
I've started on this. Will update at the RCM TEam day on 1st August :)
