### ISSUE TITLE
[INDUCTION] Andre Piza

### ISSUE THREAD

**Issue by EKaroune** [alan-turing-institute/open-research-community-management#307]
# Turing Community Managers and Team Member Induction and Onboarding - checklist

*This issue should be created by new Community Managers or collaborators of the Turing's Tools, Practices and Systems programme who have discussed their potential engagement and participation within the Open Research Community Building Team. Other members interested in the work of this team should engage with the team members via The Turing Way project and community resources - see details on [The Turing Way GitHub repository](https://github.com/alan-turing-institute/the-turing-way)*

- [x] Working from home equipment 
    - [x] Laptop
    - [-] Monitor 
    - [x] Peripherals (keyboard, mouse, camera, microphone) 
    - [-] Any other WfH equipment required (eligibility for expenses to check with HR)
- [x] Project manager meeting (onboarding on the project)
- [ ] Setting expectation for when we meet
    - [x] 1:1 meetings
        - [ ] TPS Director
        - [-] Programme Manager
        - [-] Project Manager
        - [x] Community Building Team
        - [ ] Other project stakeholders
        - [-] Business team
        - [x] REG team
        - [-] Training Team
        - [ ] RAM Team
    - [x] Weekly RCM meetings
    - [x] Weekly Co-working
    - [x] Informal chats details
    - [x] Access to group repo, docs and calendars
    - [x] Introduce TPS projects
        - [ ] The Turing Way (core membership onboarding), see [Ways of Working](https://github.com/alan-turing-institute/the-turing-way/blob/main/ways_of_working.md)
        - [ ] Open Life Science
- [x] Slack channels and workspaces
    - [x] Add them to relevant channels and workspace
- [x] Events
    - [x] Send calendar invite of Collaboration Cafe
    - [x] The Turing Way reading group and book clubs
    - [x] TPS coffee chats
- [x] Their bio and project details to add on the Turing website
- [x] Make introductions with the following people
        - [ ] Training team
        - [ ] REG team: Jim Madge
        - [ ] Whitaker lab
        - [x] TPS
        - [-] Communications Team 
        - [-] Relevant Programme Management Team member (e.g. Harriet/Hannah)
        - [-] Relevant Partnerships Team member 
        - [-] Relevant Events Team member 
- [x] Documents/ locations to share with them? 
	- [x] Sharepoint
	- [x] Turing Complete
	- [x] GitHub
	- [x] HackMD
	- [x] Turing projects
- [x] Request for bio via Topdesk

**Comment by EKaroune** [comment]
Induction meeting organised for 17th May - actual start date is 20th May.

**Comment by cassgvp** [comment]
pinging @andrepiza here :)

**Comment by EKaroune** [comment]
I've added a short blurb about data/culture to our webpage and changed your job title on your own page. 
Our webpage is here: https://www.turing.ac.uk/research/research-programmes/tools-practices-and-systems/community-management-and-open-research

Please send a bio so I can update and also check the project blurb is ok

**Comment by andrepiza** [comment]
Biog sent a while ago (commenting to record closing this action)

**Comment by EKaroune** [comment]
All completed.
